select PRODUCTO from vw_ptv_ProductoGestionEspecialidad

SELECT TOP (100) PERCENT PRD.PRD_ID, ISNULL(EPR.TIP_DESCRIPCION, 'SIN ESPECIALIDAD') AS ESPECIALIDAD_GESTOR_CALL, ISNULL(USU.USU_NOMBRES, 'SIN GESTOR') AS GESTOR_CALL, USU.USU_LOGIN, PRD.PRU_ID, 
                  PRD.PRU_IDC, PRD.PRODUCTO, USU.USU_ESTADO, UES.UES_ESTADO, PES.PES_ESTADO, USU.USU_ID, PRD.CODIGO_SAP
FROM     (SELECT TIP_ID, TIP_TIPO, TIP_CODIGO, TIP_DESCRIPCION, TIP_ORDEN, TIP_ID_PADRE, TIP_ES_PADRE, TIP_ESTADO, TIP_USUARIO_CREA, TIP_FECHA_CREA, TIP_USUARIO_MOD, TIP_FECHA_MOD
                  FROM      BDD_GENERAL.dbo.GEN_TIPO
                  WHERE   (TIP_TIPO = 'ESPECIALIDAD_PRD') AND (TIP_ESTADO = 1)) AS EPR INNER JOIN
                  BDD_GENERAL.dbo.GEN_USUARIO_ESPECIALIDAD AS UES ON EPR.TIP_CODIGO = UES.UES_TIPO_COD_ESPECIALIDAD INNER JOIN
                  BDD_GENERAL.dbo.GEN_USUARIO AS USU ON UES.USU_ID = USU.USU_ID LEFT OUTER JOIN
                  dbo.PTV_PRODUCTO_ESPECIALIDAD AS PES ON EPR.TIP_CODIGO = PES.PES_TIPO_COD_ESPECIALIDAD RIGHT OUTER JOIN
                  dbo.vw_ptv_producto_unidad AS PRD ON PES.PRD_ID = PRD.PRD_ID
WHERE  (USU.USU_ESTADO = 1) AND (UES.UES_ESTADO = 1)