select * from PTV_TIPO_PRODUCTO where TPR_DESCRIPCION like 'set multi%'
select * from PTV_PRODUCTO where TPR_ID = 10868
select * from PTV_PRODUCTO_UNIDAD where PRD_ID = 124094
 
update PTV_PRODUCTO set CAT_ID = 88 where PRD_ID =124094
 
select * from PTV_CATEGORIA where CAT_ID =88
 
select * from PTV_TIPO_PRODUCTO where TPR_DESCRIPCION like 'cloruro de%'
select * from PTV_PRODUCTO where TPR_ID = 314
 
select * from PTV_DETALLE_COTIZACION where COT_ID = 268 and PRU_ID = 125631
select * from PTV_COTIZACION where COT_ID =268

SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'PTV_PRODUCTO'
ORDER BY ORDINAL_POSITION;

